### ISSUE TITLE
Exporting org with org-pdftools links results in incorrect link to source PDF

### ISSUE THREAD

**Issue by tmalsburg** [fuxialexander/org-pdftools#29]
I have an org file with notes about some manuscript (PDF) with org-pdflinks.  When I export the notes to PDF, there are links in the resulting PDF but their URLs are incorrect.  Evince says the link is the local path of the notes followed by the absolute path of the manuscript PDF.  Needless to say, these links don't work.

**Comment by randomwangran** [comment]
I guess it is a long term goal for this project:

> [(Long-term) Org <-> PDF Annotation converter.](https://github.com/fuxialexander/org-pdftools/tree/67964a57abb9d94091e6d06afa8bd5a521c818ae#planed-features)

**Comment by fuxialexander** [comment]
Actually no. The long term goal was talking about syncing annotation comment between org file and PDF annotation.

This specific issue should be fixed with several recent commits. Please have a check.

**Comment by tmalsburg** [comment]
It's still not working but I get the impression that the PDF viewer (evince) is to blame.  On mouse over I get a popup showing the correct path. It's only when I click on the link that I get an error about the incorrect path. When I test with pdftools the link works as expected.

**Comment by tmalsburg** [comment]
(That long term goal sounds pretty cool.)
